import 'package:flutter/material.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'text_field_model.freezed.dart';

@freezed
class TextFieldModel with _$TextFieldModel {
  const factory TextFieldModel({
    required TextEditingController controller,
    required FocusNode focusNode,
    required String labelText,
    required String hintText,
    required String helperText,
    required String? errorText,
  }) = _TextFieldModel;
}